name: dinov2_lite
channels:
  - defaults
dependencies:
  - ca-certificates=2023.12.12=hecd8cb5_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.13=hca72f7f_0
  - pip=23.3.1=py39hecd8cb5_0
  - python=3.9.18=h5ee71fb_0
  - readline=8.2=hca72f7f_0
  - setuptools=68.2.2=py39hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - tk=8.6.12=h5d9f67b_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.41.2=py39hecd8cb5_0
  - xz=5.4.6=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
      - appdirs==1.4.4
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - filelock==3.13.1
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.42
      - huggingface-hub==0.21.3
      - idna==3.6
      - importlib-resources==6.1.2
      - iopath==0.1.10
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - kornia==0.7.1
      - loralib==0.1.2
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.2.1
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pillow==10.2.0
      - portalocker==2.8.2
      - pretrainedmodels==0.7.4
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pyyaml==6.0.1
      - requests==2.31.0
      - safetensors==0.4.2
      - scipy==1.12.0
      - segmentation-models-pytorch==0.3.3
      - sentry-sdk==1.40.6
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.12
      - tabulate==0.9.0
      - termcolor==2.4.0
      - timm==0.9.2
      - torch==2.2.1
      - torchvision==0.17.1
      - tqdm==4.66.2
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - wandb==0.16.3
      - yacs==0.1.8
      - zipp==3.17.0
prefix: /Users/dw/miniconda3/envs/dinov2_lite
